### ISSUE TITLE
[Bug] Inaccurate headings and readme saying Deploy to a production environment based on labels

### ISSUE THREAD

**Issue by gitgithan** [skills/deploy-to-azure#55]
In `5-deploy-to-prod-environment.md` it says `Step 5: Deploy to a production environment based on labels`.
In `X-finish.md` it says `Deploy to a production environment based on labels`.

However the exercises never deployed to production based on labels. It was based on push to main in 
`.github/workflows/deploy-prod.yml`
```
name: Deploy to production

on:
  push:
    branches:
      - main
```
Descriptions may have been outdated.
