### ISSUE TITLE
[Bug] Inaccurate comments in `4-deploy-to-staging-environment.yml` make search for terms confusing 

### ISSUE THREAD

**Issue by gitgithan** [skills/deploy-to-azure#56]
```
# This will run after the "Configure Azure environment" workflow
# completes on the azure-configuration branch
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to staging"]
    types: [completed]
    branches: [staging-test]
 ```
 
 
 Should be 
`This will run after the "Deploy to staging" workflow` and `completes on the staging-test branch`
