### ISSUE TITLE
[Bug] Step 4 fails if GitHub username contains an uppercase letter

### ISSUE THREAD

**Issue by Joserra13** [skills/deploy-to-azure#96]
### Summary

As you can see, my GitHub username contains an uppercase letter and when you build the docker image, it fails when starting the ttt-app in azure because of the following logs I got from **Deployment Center** -> **Logs** in my Azure Web App:

`
2024-11-25T17:32:44.166Z INFO - Pulling image: ghcr.io/Joserra13/deploy-to-azure/Joserra13-azure-ttt:<what_i_think_it_is_a_token>
`
`
2024-11-25T17:32:44.190Z ERROR - DockerApiException: Docker API responded with status code=BadRequest, response={"message":"invalid reference format: repository name must be lowercase"}
`

I changed the DOCKER_IMAGE_NAME in the env variables of the workflow for the **Build-Docker-Image** job from: `DOCKER_IMAGE_NAME: Joserra13-azure-ttt` to `DOCKER_IMAGE_NAME: joserra13-azure-ttt`

When running the job it was successful, but still the Azure Web App logs looked the same as above, but with the updated image name in lowercase:

`
2024-11-25T17:32:44.166Z INFO - Pulling image: ghcr.io/Joserra13/deploy-to-azure/joserra13-azure-ttt:<what_i_think_it_is_a_token>
`
`
2024-11-25T17:32:44.190Z ERROR - DockerApiException: Docker API responded with status code=BadRequest, response={"message":"invalid reference format: repository name must be lowercase"}
` 

So, what I did, was to hardcode the ${{ github.repository }} variable from the **Build-Docker-Image** job at the step **Extract metadata (tags, labels) for Docker** to `joserra13/deploy-to-azure` so, my uppercase letter in the username is set to lowercase. It should look like this:
```
      - name: Extract metadata (tags, labels) for Docker (hardcodename)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.IMAGE_REGISTRY_URL}}/joserra13/deploy-to-azure/${{env.DOCKER_IMAGE_NAME}}
          tags: |
            type=sha,format=long,prefix=
```
And this worked.
